schema:
  - "https://lab.lectrum.ua/graphql" 
documents:
  - "./src/constants/graphql/**/*.graphql"
generates:
  ./src/types/__generated__/graphql.ts:
    plugins:
      - typescript
      - typescript-operations
      - typescript-react-apollo